<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15438" started-at="2018-06-27T11:28:50Z" finished-at="2018-06-27T11:29:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15438" started-at="2018-06-27T11:28:50Z" finished-at="2018-06-27T11:29:05Z">
      <class name="keyword.MyTest">
        <test-method status="PASS" signature="calllaunchBrowser()[pri:0, instance:keyword.MyTest@27a8c74e]" name="calllaunchBrowser" is-config="true" duration-ms="7366" started-at="2018-06-27T11:28:50Z" finished-at="2018-06-27T11:28:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- calllaunchBrowser -->
        <test-method status="PASS" signature="callLoginPage()[pri:0, instance:keyword.MyTest@27a8c74e]" name="callLoginPage" duration-ms="2046" started-at="2018-06-27T11:28:57Z" finished-at="2018-06-27T11:28:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callLoginPage -->
        <test-method status="PASS" signature="callBlankCredentials()[pri:1, instance:keyword.MyTest@27a8c74e]" name="callBlankCredentials" duration-ms="322" started-at="2018-06-27T11:28:59Z" finished-at="2018-06-27T11:28:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callBlankCredentials -->
        <test-method status="PASS" signature="callCorrectUsername()[pri:2, instance:keyword.MyTest@27a8c74e]" name="callCorrectUsername" duration-ms="871" started-at="2018-06-27T11:28:59Z" finished-at="2018-06-27T11:29:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callCorrectUsername -->
        <test-method status="PASS" signature="callEnteredPassword()[pri:3, instance:keyword.MyTest@27a8c74e]" name="callEnteredPassword" duration-ms="953" started-at="2018-06-27T11:29:00Z" finished-at="2018-06-27T11:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callEnteredPassword -->
        <test-method status="FAIL" signature="callCorrectCredentials()[pri:4, instance:keyword.MyTest@27a8c74e]" name="callCorrectCredentials" duration-ms="3845" started-at="2018-06-27T11:29:01Z" finished-at="2018-06-27T11:29:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at keyword.MyTest.callCorrectCredentials(MyTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callCorrectCredentials -->
      </class> <!-- keyword.MyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
